# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Azure Pipelines

steps:
- task: UseNode@1
  displayName: 'Use Node 15.x'
  inputs:
    version: 15.x



- task: Npm@1
  displayName: 'npm install angular'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install @angular/cli -g'



- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false



- script: |
   echo ng build --prod
   
  displayName: 'build the angular up'



- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifact: 'Angular-Prod'



- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: a1-app-prod'
  inputs:
    azureSubscription: 'Azure for Students (e41b529e-f33d-4ff1-b953-6988f18bba25)'
    appType: webAppLinux
    WebAppName: 'a1-app-prod'
    packageForLinux: '$(System.DefaultWorkingDirectory)'
    RuntimeStack: 'NODE|14-lts'



